Module 5

In this lesson you will learn about:
    Explain the use of the HTTP protocol using the Requests Library method
    Describe how the URL Request Response HTTP protocol works
    Learn to apply simple, open-source APIs
    Perform basic webscraping using Python
    Work with different file formats using Python
    Explain the difference between APIs and REST APIs
    Summarize how APIs receive and send information

What is the result of the following operation:

In [1]:
import numpy as np

np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [2]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

How many rows are in the following numpy array?

In [4]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Is it possible to perform the following operation?

In [5]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B)

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

What is the result of the following lines of code:

In [6]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [7]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [8]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])